"""add optional sme fields

Revision ID: 1b5f8c66a2f5
Revises: 98b952bf0f32
Create Date: 2026-05-03 21:21:40.815197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5f8c66a2f5'
down_revision: Union[str, None] = '98b952bf0f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smes', sa.Column('role', sa.String(), nullable=True))
    op.add_column('smes', sa.Column('department', sa.String(), nullable=True))
    op.add_column('smes', sa.Column('responsible_products', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('smes', sa.Column('sub_expertise', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smes', 'sub_expertise')
    op.drop_column('smes', 'responsible_products')
    op.drop_column('smes', 'department')
    op.drop_column('smes', 'role')
    # ### end Alembic commands ###
