"""add interview fields and query log

Revision ID: 8c96f40b962e
Revises: 1b5f8c66a2f5
Create Date: 2026-05-04 03:50:06.590009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c96f40b962e'
down_revision: Union[str, None] = '1b5f8c66a2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_query_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('response_type', sa.String(), nullable=True),
    sa.Column('related_sme_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_sme_id'], ['smes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_topic_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('topic_index', sa.Integer(), nullable=False),
    sa.Column('topic_question', sa.Text(), nullable=False),
    sa.Column('refined_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'topic_index')
    )
    op.add_column('interview_turns', sa.Column('refined_summary', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('requested_by', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('admin_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'admin_note')
    op.drop_column('interviews', 'requested_by')
    op.drop_column('interview_turns', 'refined_summary')
    op.drop_table('interview_topic_summaries')
    op.drop_table('user_query_log')
    # ### end Alembic commands ###
